"""features table

Revision ID: 808368752729
Revises: 
Create Date: 2020-03-22 03:05:23.335600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '808368752729'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('demise_place', sa.String(), nullable=True),
    sa.Column('demise_date', sa.Date(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('features')
    # ### end Alembic commands ###
