"""features table

Revision ID: b4fb3196dad4
Revises: d0eb321f5e0b
Create Date: 2020-03-22 14:09:59.822728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4fb3196dad4'
down_revision = 'd0eb321f5e0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('features', sa.Column('demise_how', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('features', 'demise_how')
    # ### end Alembic commands ###
