"""features table

Revision ID: d0eb321f5e0b
Revises: 808368752729
Create Date: 2020-03-22 14:00:16.413835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0eb321f5e0b'
down_revision = '808368752729'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('features', sa.Column('demise_reason', sa.String(), nullable=True))
    op.add_column('features', sa.Column('home_town', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('features', 'home_town')
    op.drop_column('features', 'demise_reason')
    # ### end Alembic commands ###
